server:
  port: 8080
  servlet:
    context-path: /

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  devtools:
    livereload:
      enabled: true

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:9006/statistics
    username: root
    password: 1234

mybatis:
  mapper-locations: classpath:mapper/**.xml
  type-aliases-package: com.practice.commento.dto